remove: nats-top due to broken tests
We don't really need nats-top (and always get it in PATH with a
nix-shell), and it's broken at the moment:

```
--- FAIL: TestMonitoringTLSConnectionUsingRootCA (0.03s)
    toputils_test.go:373: Could not monitor number of cores. got: 0
--- FAIL: TestMonitoringTLSConnectionUsingRootCAWithCerts (0.03s)
    toputils_test.go:406: Could not monitor number of cores. got: 0
FAIL
FAIL    github.com/nats-io/nats-top/util        0.160s
FAIL
error: Cannot build '/nix/store/54anagykykv9q9prz58v24cxnk6s77q4-nats-top-0.6.3.drv'.
```